### ISSUE TITLE
Enabling News plugin breaks ticket description

### ISSUE THREAD

**Issue by roshanroche** [pluginsGLPI/news#53]
Hello ,
there are few issues with news plugin on GLPI 9.2.x ,
while enabled , the tinymce doesnt load anymore for ticket description field. ( even after refreshing the page ). the same issue happens in news plugin description field ( but upon refresh the tincymce loads ).
please refer to the images attached below.
![image](https://user-images.githubusercontent.com/22425503/37889258-885a9900-30dc-11e8-810c-45eccfd51c62.png)
![image](https://user-images.githubusercontent.com/22425503/37889303-b1f14138-30dc-11e8-80bb-46137976d2b1.png)
![image](https://user-images.githubusercontent.com/22425503/37889335-d059c4a6-30dc-11e8-8b90-c315ae2e4493.png)
![image](https://user-images.githubusercontent.com/22425503/37889361-fada2ae0-30dc-11e8-84d2-d965103b3a47.png)

![image](https://user-images.githubusercontent.com/22425503/37889426-4ca46df4-30dd-11e8-9baf-6ca6f4a97fa7.png)
![image](https://user-images.githubusercontent.com/22425503/37889466-8884bcde-30dd-11e8-86e7-8b31a75a225e.png)
other issues have already reported by other users , 
1. Can not close alert on home page even though close alert option is selected
2. alert is showed on home page even when show alert on home page is set to no.
3. tinymce does not load on 1st page load. ( after refresh it loads )

**Comment by cedric-anne** [comment]
Hello,

The bug that prevent tinyMCE to be shown in ticket form is fixed by https://github.com/pluginsGLPI/news/pull/43 on version 1.3.4.

For other issues :
1) The problem that prevent closing of alerts on home page will be fixed by https://github.com/pluginsGLPI/news/pull/51 on next release.

2) There is no "show alert on home page" option. If you are talking about displaying on login page, I tried on GLPI 9.2.3 with News plugin 1.3.4 and behaviour seems correct except in a specific case. I opened an issue related to this on GLPI project: https://github.com/glpi-project/glpi/issues/3992.

3) The problem that prevent TinyMCE to be used at first display will be fixed by https://github.com/pluginsGLPI/news/pull/47 on next release.
